### ISSUE TITLE
can't compile the ino file

### ISSUE THREAD

**Issue by new2mc** [arkypita/ESP8266-SerialWebSocket#6]
hi,

1st of all: thanks for your lasergrbl project and providing SW and Wifi s upport sketch!that's great.
Unfortunately I am not yet in the state to try it.
I am pretty new to the whole programming and mc stuff.
I am using a arduino uno r3 clone with on Board esp8266 and was able to flash it with the blink sketch which is running fine so far. I am using Arduino IDE 1.8.9 on Win10 64bit.
I followed your instructions and downloaded the libraries and packages according to your instructions. After loading the websocketsserver.ino file (no modification to the code), and selecting "generic esp8266" board not modifying any settings there and the correct COM Port, I tried to compile the sketch. the result is see attached txt file which I copied from the console output.

[errorlog.txt](https://github.com/arkypita/ESP8266-SerialWebSocket/files/3364982/errorlog.txt)

Am I doing something wrong? there are no missing files as far as I can tell and there seems to be a problem with the conversion?! I am lost here. 

thanks for your help! cheers.

**Comment by new2mc** [comment]
Hey,

Nobody there to help me?
Is it maybe an issue with compatibility of the versions of the installed libraries? In the library manager I always chose the latest version.

Thanks for help.

**Comment by arkypita** [comment]
Yes, it should be something like this. Maybe some library has changed since i havr developed websocket sketch.
Now i have not the time to look at this. Try to understand the problem by yourself by identify what is the error (not warning but error) that stop the compiling process and google for that

**Comment by arkypita** [comment]
Error is:

undefined reference to `WebSockets::write(WSclient_t*, unsigned char*, unsigned int)'

**Comment by new2mc** [comment]
Hi arkypita,

Thanks a lot. finally I managed to get it running. WebSocketsServer.cpp and WebSockets.cpp file was missing in the libraries folder.
The warnings do not seem to prevent compiling...
thanks again. issue closed.
Cheers
